2018-05-02 13:40:51 Error: [NotFoundException] Not Found
Request URL: /cakephp-2.7.6/
Stack Trace:
#0 /var/www/html/cakephp-2.7.6/lib/Cake/View/View.php(971): include()
#1 /var/www/html/cakephp-2.7.6/lib/Cake/View/View.php(933): View->_evaluate('/var/www/html/c...', Array)
#2 /var/www/html/cakephp-2.7.6/lib/Cake/View/View.php(473): View->_render('/var/www/html/c...')
#3 /var/www/html/cakephp-2.7.6/lib/Cake/Controller/Controller.php(960): View->render('home', NULL)
#4 /var/www/html/cakephp-2.7.6/app/Controller/PagesController.php(68): Controller->render('home')
#5 [internal function]: PagesController->display('home')
#6 /var/www/html/cakephp-2.7.6/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#7 /var/www/html/cakephp-2.7.6/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/html/cakephp-2.7.6/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#9 /var/www/html/cakephp-2.7.6/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 /var/www/html/cakephp-2.7.6/index.php(41): require('/var/www/html/c...')
#11 {main}
2018-05-02 15:23:11 Error: [NotFoundException] Not Found
Request URL: /cakephp-2.7.6/
Stack Trace:
#0 /var/www/html/cakephp-2.7.6/lib/Cake/View/View.php(971): include()
#1 /var/www/html/cakephp-2.7.6/lib/Cake/View/View.php(933): View->_evaluate('/var/www/html/c...', Array)
#2 /var/www/html/cakephp-2.7.6/lib/Cake/View/View.php(473): View->_render('/var/www/html/c...')
#3 /var/www/html/cakephp-2.7.6/lib/Cake/Controller/Controller.php(960): View->render('home', NULL)
#4 /var/www/html/cakephp-2.7.6/app/Controller/PagesController.php(68): Controller->render('home')
#5 [internal function]: PagesController->display('home')
#6 /var/www/html/cakephp-2.7.6/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#7 /var/www/html/cakephp-2.7.6/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/html/cakephp-2.7.6/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#9 /var/www/html/cakephp-2.7.6/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 /var/www/html/cakephp-2.7.6/index.php(41): require('/var/www/html/c...')
#11 {main}
2018-05-02 15:32:34 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /cakephp-2.7.6/
Stack Trace:
#0 /var/www/html/cakephp-2.7.6/lib/Cake/Model/ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 /var/www/html/cakephp-2.7.6/lib/Cake/Model/Model.php(3626): ConnectionManager::getDataSource('default')
#2 /var/www/html/cakephp-2.7.6/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#3 /var/www/html/cakephp-2.7.6/lib/Cake/Model/Model.php(3653): Model->setSource('news')
#4 /var/www/html/cakephp-2.7.6/lib/Cake/Model/Model.php(3031): Model->getDataSource()
#5 /var/www/html/cakephp-2.7.6/lib/Cake/Model/Model.php(3003): Model->_readDataSource('all', Array)
#6 /var/www/html/cakephp-2.7.6/app/Controller/AppController.php(103): Model->find('all', Array)
#7 /var/www/html/cakephp-2.7.6/app/Controller/HomesController.php(13): AppController->beforeFilter()
#8 /var/www/html/cakephp-2.7.6/lib/Cake/Event/CakeEventManager.php(243): HomesController->beforeFilter(Object(CakeEvent))
#9 /var/www/html/cakephp-2.7.6/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#10 /var/www/html/cakephp-2.7.6/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#11 /var/www/html/cakephp-2.7.6/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(HomesController), Object(CakeRequest))
#12 /var/www/html/cakephp-2.7.6/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 /var/www/html/cakephp-2.7.6/index.php(41): require('/var/www/html/c...')
#14 {main}
2018-05-02 16:04:11 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:04:11 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:04:32 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:04:32 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:06:48 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:06:48 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:06:50 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:06:50 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:06:54 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:06:54 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:06:58 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:06:58 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:06:59 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:06:59 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:25:14 Error: [MissingControllerException] Controller class Diagnostics.aspController could not be found.
Exception Attributes: array (
  'class' => 'Diagnostics.aspController',
  'plugin' => NULL,
)
Request URL: /Diagnostics.asp
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-05-02 16:32:33 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:32:33 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:39:24 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:39:24 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 16:42:26 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 16:42:26 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 17:50:14 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 17:50:14 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 18:27:08 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 18:27:08 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 18:43:13 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 18:43:13 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 18:53:24 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2018-05-02 18:53:24 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-05-02 19:05:59 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'file_type' doesn't have a default value
Request URL: /users/view/app-info?shop_id=96&sort%5B1%5D=28.png&sort%5B2%5D=10173000309.jpg&sort%5B3%5D=lgf01a201408220400.jpg&exist_img%5B1%5D=28.png&exist_img%5B2%5D=10173000309.jpg&exist_img%5B3%5D=lgf01a201408220400.jpg&item=&introduction=%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F&shop_name=%3F%3F%3F%3F%3F%3F%3F%3F&shop_name_kana=%3F%3F%3F%3F%3F%3F%3F%3F&shop_address=%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F1-1-1&hours_start=&hours_start_min=&hours_end=&hours_end_min=&openning_hours=AM11%3A00%3FAM5%3A00&holidays=%3F%3F%3F%3F&phone=03-1111-2222&fax=03-1234-5678&url=&email=test%40gmail.com&facebook=&twitter=&splash_hidden_name=20015828.png&latitute=21.0277644&longtitute=105.83415979999995&geo_address=Ha+Noi&action=save
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `co...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `co...')
#3 /var/www/html/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Media), Array, Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/html/cakephp/app/Controller/AppInformationsController.php(197): Model->save(Array)
#6 /var/www/html/cakephp/app/Controller/AppInformationsController.php(56): AppInformationsController->save_all()
#7 [internal function]: AppInformationsController->index()
#8 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(AppInformationsController), Array)
#9 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AppInformationsController), Object(CakeRequest))
#11 /var/www/html/cakephp/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2018-05-02 19:32:53 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'agent_id' doesn't have a default value
Request URL: /customers/register?shop_id=&customer_id=&lastname=dfsdf&firstname=sdfs&lastname_kana=sdfsdf&firstname_kana=dfsdf&contact=sdfsdf&birthday=1980-01-17&gender=%E7%94%B7%E6%80%A7&area_id=13&membership_id=sdfsdf&email=sdfsdf%40gmail.com
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `co...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `co...')
#3 /var/www/html/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(User), Array, Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/html/cakephp/app/Controller/CustomersController.php(375): Model->save(Array)
#6 [internal function]: CustomersController->register()
#7 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(CustomersController), Array)
#8 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CustomersController), Object(CakeRequest))
#10 /var/www/html/cakephp/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2018-05-02 19:50:40 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'conexi.User.platform_type' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /actions/get_data_list?year=2018
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1118): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(User), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('all', Array)
#6 /var/www/html/cakephp/app/Controller/ActionsController.php(97): Model->find('all', Array)
#7 [internal function]: ActionsController->get_data_list()
#8 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ActionsController), Array)
#9 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ActionsController), Object(CakeRequest))
#11 /var/www/html/cakephp/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2018-05-02 20:41:12 Error: [MissingControllerException] Controller class Diagnostics.aspController could not be found.
Exception Attributes: array (
  'class' => 'Diagnostics.aspController',
  'plugin' => NULL,
)
Request URL: /Diagnostics.asp
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
